mongoDBConfig: &mongoDBConfig
  code: mongodb
  driverName: mongodb
  urlAddress: "mongodb+srv://hungvu:LavgCNVqqTwm3sbj@cluster0-whcio.mongodb.net/test?retryWrites=true&w=majority"
  dbName: "shortener"
  timeout: 30
redisConfig: &redisConfig
  code: redis
  driverName: redis
  urlAddress: "redis://redis-18321.c1.ap-southeast-1-1.ec2.cloud.redislabs.com:18321"
  password: IdE6uMBbFi5St2YBxK4rEAoL4ObbgnDs
inMemoryConfig: &inMemoryConfig
  code: inmemory
useCaseConfig:
  shortenURL:
    code: shortenURL
    redirectRepoConfig: &redirectRepoConfig
      code: redirectRepo
      dataStoreConfig: *inMemoryConfig